### ISSUE TITLE
[Feature request] Formatting Support

### ISSUE THREAD

**Issue by DavidRLTG** [0x7c13/Notepads#1145]
**Is your feature request related to a problem? Please describe.**
Not really! Just something I'd really love to be added.

**Describe the solution you'd like**
**Bolded**, _Italic_, or underlined text is not supported!
I would really love support for this to be added, as it would help quite a bit with some documents, and their looks.

**Describe alternatives you've considered**
None. I just can't find a better text editor that also supports formatting :(

**Additional context**
I dunno what to add here..

**Comment by 0x7c13** [comment]
Notepads is a plain text editor not rich text editor..
