### ISSUE TITLE
[Bug] The app resizes very slowly, and stutters when resized

### ISSUE THREAD

**Issue by DavidRLTG** [0x7c13/Notepads#1146]
**Describe the bug**
Basically: the app is very slow while being resized, and somehow it's just not as smooth as normal notepad when resized. it stutters, and slows down.

**To Reproduce**
Simply, open a text file with over 40 lines, and start quickly resizing the window.

**Expected behavior**
I did not expect stuttering during resizing.

**Screenshots**
I can't screenshot **that**..

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 22000.318
 - Version v1.4.8.0

**Additional context**
I dunno D:

**Comment by 0x7c13** [comment]
This is expected if you have large chunks of text with word-wrap enabled.

**Comment by DavidRLTG** [comment]
Ah, I see.
Could it *somehow* be improved in the future?
not saying it has to be improved but, hmm!

**Comment by 0x7c13** [comment]
Notepads uses WinRT RichEdit control provided by MSFT, it is a black box and it can only be improved by Microsoft.

**Comment by DavidRLTG** [comment]
Ah, got it. Thanks for the explanation!
