### ISSUE TITLE
[Feature request] Improve row and linebreak selection

### ISSUE THREAD

**Issue by vajnaivik** [0x7c13/Notepads#1161]
**Is your feature request related to a problem? Please describe.**
When I'd like to reorder rows or multiple rows in a text document, I can't easily select the text together with the previous linebreak.
What happens when selecting a line and moving the mouse up one line, is that: 
- either only the line gets selected with no linebreaks,
- the line gets selected with the following linebreak
- or both the previous and the following linebreaks are selected.

**Describe the solution you'd like**
In Windows Notepad (and most other text editors), selection with linebreaks feels much more predictable, when moving the mouse up a line, the cursor follows, and only the previous linebreak gets selected.
The behavior I mean, is basically what happens when you are the end of a line with the cursor, and press shift + up arrow once (when the previous line is shorter of course).

**Describe alternatives you've considered**
I can use the keyboard alternatively, but that takes extra steps each time, and sometimes that also highlights the following linebreak somehow...

**Additional context**
![image](https://user-images.githubusercontent.com/61936589/198580596-c94f782a-192d-4078-a705-2aced6aa04bb.png)
![image](https://user-images.githubusercontent.com/61936589/198580672-638a8038-1550-4a71-9449-a43caed1746b.png)

**Comment by vajnaivik** [comment]
One other alternative I found is:
Starting the selection from the top row, and going to the end of the lower line.
This is also cumbersome, because you have to end precisely on the end of the lower line, otherwise the next linebreak will also be selected.
![image](https://user-images.githubusercontent.com/61936589/199447659-bffde3a7-f8e4-45fa-945e-0c67d44acd91.png)

**Comment by 0x7c13** [comment]
Try alt + ^ or alt + V (arrow key)

**Comment by vajnaivik** [comment]
@0x7c13 As I mentioned in the original post, using the keyboard is a viable alternative, but that takes extra steps each time, can't be done without letting go of the mouse and the selection feels inconsistent this way.

**Comment by 0x7c13** [comment]
This is how the underline WinRT richedit text control implemented by Microsoft. I cannot do anything unless they change the way how it works or giving us option to configure its behavior like what you described earlier.

**Comment by vajnaivik** [comment]
Well that's too bad, thanks for the reply tho.
Should I close the issue than?
