### ISSUE TITLE
[Bug]American keyboard input error in Chinese language

### ISSUE THREAD

**Issue by diyudule** [0x7c13/Notepads#1167]
**Describe the bug**
When I use an American keyboard to input English in the Simplified Chinese language, I cannot type the letters directly, but the letters with underlines and separators appear, and pressing the space bar at this time will type Simplified Chinese instead of English letters

**Screenshots**
![QQ截图20221125233528](https://user-images.githubusercontent.com/29426186/204018454-618558aa-a6af-45be-bb19-c6af524f6d22.png)
![QQ截图20221125233540](https://user-images.githubusercontent.com/29426186/204018487-07ea193b-ccaa-44ca-8987-b90bdea52b08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.1316
 - Version v1.4.8.0

**Comment by 0x7c13** [comment]
This is related to your IME, not specifically tight to Notepads. Please try another IME to see if it works properly.
