### ISSUE TITLE
[Feature request] Integrate with Git

### ISSUE THREAD

**Issue by fagbenjaenoch** [0x7c13/Notepads#1189]
**Describe the solution you'd like**
I'd like notepad to integrate with git since it's able to work with markdown files reducing the stress of switching to the terminal or any other GUI tool.

**Comment by fred913** [comment]
Disagree. As Notepads has almost **no** support for file trees (working in directories like any other IDE), it's unsuitable and unnecessary to add Git Integration, whereas Git works with folders best.

**Comment by fagbenjaenoch** [comment]
never thought of that, thanks for the insight
