### ISSUE TITLE
[Feature request] Open in Notepads entry

### ISSUE THREAD

**Issue by qzcz** [0x7c13/Notepads#1201]
**Is your feature request related to a problem? Please describe.**
Is it possible to add an entry `Open in Notepads` in the context menu? Like in the `Windows Terminal` application.
I want to quickly open and save the selected text with Notepads. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/220720769-eb8690dd-992d-4894-ba34-37ad091048e1.png)

</details>

**Comment by Riki7745** [comment]
I made that, via Registry (HKCR\*\shell\Editwithnotepad), it worked few days but now I have tree error messages when I try to use it again : sharedlibray.dll, mrt100_app.dll and VCRUNTIME140_APP.dll, I updated tons of things, but it doesn't work anymore...

**Comment by Riki7745** [comment]
> I made that, via Registry (HKCR*\shell\Editwithnotepad), it worked few days but now I have tree error messages when I try to use it again : sharedlibray.dll, mrt100_app.dll and VCRUNTIME140_APP.dll, I updated tons of things, but it doesn't work anymore...

desinstall, reinstall...it works...
