### ISSUE TITLE
Alternative download (zip or exe), instead of Microsoft Store

### ISSUE THREAD

**Issue by humphreylee** [0x7c13/Notepads#1229]
**Is your feature request related to a problem? Please describe.**
Due to certain IT policy, I am not able to install Notepads from Microsoft Store.

**Describe the solution you'd like**
Please provide exe or zip file download for Windows x86_64 from github.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Thanks.

**Comment by bw1faeh0** [comment]
You can install the *.msixbundle from the download page without using the store:

run this in an admin power shell:
` Add-AppxPackage \path\to\Notepads_1.4.9.0_x86_x64_arm64.msixbundle`

**Comment by humphreylee** [comment]
Unfortunately, I don't have Admin. Probably, I am looking for a portable type.

**Comment by humphreylee** [comment]
Just noticed the *.msibundle can be installed as it is (double-clicking it). So, closing this issue. However, I still prefer portable binary.
