### ISSUE TITLE
[Feature request] Drag & Drop to open a file

### ISSUE THREAD

**Issue by jkhamroev** [0x7c13/Notepads#1242]
It would be greate to have a drag & drop feature to open a file

**Additional context**

![ezgif-1-812b675ba6](https://github.com/0x7c13/Notepads/assets/55449509/3ebaa434-8599-4576-8afc-870629345965)

**Comment by 0x7c13** [comment]
Isn't it already supported by Notepads?

**Comment by jkhamroev** [comment]
Seems like it isn't.
Here is an example:
![ezgif-1-0d589f3128](https://github.com/0x7c13/Notepads/assets/55449509/a2ed9628-fb5e-42c6-8b0f-14b6c94253bc)

**Comment by jkhamroev** [comment]
@0x7c13
Any thoughts? Maybe it's only on my machine such problem?

**Comment by 0x7c13** [comment]
What's the version of the app?

**Comment by jkhamroev** [comment]
<img src="https://github.com/0x7c13/Notepads/assets/55449509/c3888ecd-a89b-4f24-a598-e76c1e021812" width="500"/>
