### ISSUE TITLE
High contrast selection

### ISSUE THREAD

**Issue by NicknEma** [0x7c13/Notepads#1259]
I keep the app in dark mode, and the selection is always so hard to see, because its color barely differs from that of the background, it's just a slightly lighter gray.

I would like the selected text highlight to be of a contrasting color so that it's clear what text is selected and what isn't. Either the program figures it out in its own, or it lets you customize it separately from the rest of the theme.

![image](https://github.com/0x7c13/Notepads/assets/62065135/b7743648-8f6f-4308-bf48-692e6bc5e473)

**Comment by 0x7c13** [comment]
Pick a different accent color other than grey:

![image](https://github.com/0x7c13/Notepads/assets/1166162/42127fd6-7da8-415d-97d9-73708554d680)
