### ISSUE TITLE
[Bug] Does not save in UTF-8 BOM

### ISSUE THREAD

**Issue by 8DL9** [0x7c13/Notepads#1260]
Does not save text and symbols in UTF-8 BOM encoding:

1) ![01](https://github.com/0x7c13/Notepads/assets/99109832/b2bdbeea-6a62-401f-bb70-575740519f93)

2) ![02](https://github.com/0x7c13/Notepads/assets/99109832/7e5ea6f9-0c2d-46f4-8d9c-3544fcf41ffc)

3) ![03](https://github.com/0x7c13/Notepads/assets/99109832/f46f7e1b-68dd-49cb-8984-180d9b58c87e)

**Comment by 0x7c13** [comment]
Create a new tab and it will work.
![image](https://github.com/0x7c13/Notepads/assets/1166162/3495f5fb-0e22-426a-af52-12467df685ff)
