### ISSUE TITLE
[feature request] disable or ability to hide "this is a shadow window" notification 

### ISSUE THREAD

**Issue by ivan8994** [0x7c13/Notepads#1274]
**Is your feature request related to a problem? Please describe.**
In settings, it is possible to switch to multi-windows mode, but in this case every time you open a new instance of Notepads, every time a notification appears saying "this is a shadow window", and it takes it place for about 4 secs before disappearing! 

**Describe the solution you'd like**
It would be a nice compromise to have ability to disable "this is a shadow window" notification in settings

**Describe alternatives you've considered**
Alternatively, thime of notification to be visible may be reduced to 2 secs.

**Additional context**
By default, there is no option to launch another instance of Notepads, like you normally can do with default Windows Notepad. 
This limits usage scenarios of Notepads and prevents people from starting using Notepads as a default notes app.
yes, by switching to multi-instances mode it becomes possible to open as many "new documents" for example for side-to-side usage, but the notification which appears every time on launch ruins all the experience. Not to mention, for some time later after this mode is activated, even when you open 1 fresh window it already becomes "a shadow" and the only way to get into settings is to completely delete and re-install Notepads.

**Comment by 44vince44** [comment]
@ivan8994 

> even when you open 1 fresh window it already becomes "a shadow" and the only way to get into settings is to completely delete and re-install Notepads.

This is due to a crashing notepads.exe that you can kill in the task manager. Once you've killed that crashing notepads.exe process, if you open notepads, it will show as normal, not shadow, and you'll be able to access the settings. No need to uninstall and reinstall the app.

This has happened to me also, although I don't see why notepads silently crashes...

**Comment by 44vince44** [comment]
@ivan8994 everything works OK now in version 1.5.2.0

**Comment by 909101** [comment]
agreed with the request and wanted the requested feature as well

**Comment by 0x7c13** [comment]
Agreed and removed this notification completely since I think it is too noisy: https://github.com/0x7c13/Notepads/commit/e66f0153e06eaa259e1fb05cdd7faa467dbfec49

**Comment by ivan8994** [comment]
just have tested ver. 1.5.3.0

no "this is a shadow window" notification appears now.

thank you very much for attention to this isse.

i will leave my futher suggestions in future requests.

thank you @0x7c13 and best regards
