### ISSUE TITLE
[Bug] Application suddenly shut down

### ISSUE THREAD

**Issue by higun295** [0x7c13/Notepads#1277]
**Describe the bug**
As I wrote in title, literally application suddenly shut down.

**To Reproduce**
I cannot reproduce this error clearly.
But, this is not a first time. During typing keyboard, application suddenly dead.

**Expected behavior**
Maybe, if some specific keys pressed, those are working comprehensively.

**Screenshots**
![image](https://github.com/0x7c13/Notepads/assets/42757925/e5798300-9538-4fff-bd69-922cfb529b8d)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22621.2715
 - Version 22H2

**Additional context**
Um... I can't explain it exactly, but it seems like these keys interact in a complex way and cause issues when I'm typing on the keyboard.

**Comment by 0x7c13** [comment]
Why is it Notepads-Dev, are you running a debug version of the app?

**Comment by higun295** [comment]
Wow....... I didn't know that.... 😢
I think that I installed debug version maybe.. haha
