### ISSUE TITLE
[Bug] Notepads.exe process existing when computer starts will prevent proper multiinstance use

### ISSUE THREAD

**Issue by 44vince44** [0x7c13/Notepads#1279]
**Bug description**
**CONDITIONS:** Notepads must be set to work in multiinstance mode (open in new window, not in new tab).
At startup of the computer, there is a notepads.exe process working on the system.
So, if you open any notepads windows, it will open as shadow copy.
That means that you can't access settings, because it is a shadow copy.

Workaround: kill process notepads.exe, open notepads, it will work OK from now on, until next system restart.

**To Reproduce**
Set notepads in multiinstance mode (open in new window, not in new tab)
Restart computer
Wait a few seconds
Start notepads
==> Notepads will say it's a shadow copy
Try to change settings, that's impossible because it's a shadow copy. 

**Fix suggested**
Do not make notepads autostart with system, especially when multiinstance mode selected.

**Comment by 0x7c13** [comment]
That's a good suggestion. Made these changes: [https://github.com/0x7c13/Notepads/commit/b778721876cb4908ce904221847542332a36ee99] and it will be part of next release. Let me know if that solves your problem.

**Comment by 0x7c13** [comment]
@44vince44 Try the latest release and let me know if it helps.

**Comment by 44vince44** [comment]
@0x7c13 Thanks, I have tried 1.5.2.0 and indeed, there is not more notepads.exe running when the computer is started, and multi-instance mode works correctly: no more "shadow" message when opening notepads for the first time, and settings are available.

I will continue working with it and report if I find anything else.

And thank you for the good hard work, this app is really needed on Windows 10 in dark mode !

**Comment by 44vince44** [comment]
Everything seems OK, again Thanks! Closing the issue.
