### ISSUE TITLE
Add an Option to Disable autocorrect.

### ISSUE THREAD

**Issue by KParthSingh** [0x7c13/Notepads#1283]
**Is your feature request related to a problem? Please describe.**
I'm a Data Entry Person and it's frustrating when I don't want what I'm typing to get corrected or capitalized.

**Describe the solution you'd like**
option in settings to turn off autocorrect. PLEASE.

By the way, I love this app.

**Comment by 0x7c13** [comment]
![image](https://github.com/0x7c13/Notepads/assets/1166162/91ba5dc5-d197-400a-a4f3-be0d6cad5e47)

**Comment by KParthSingh** [comment]
Oh. thanks.
