### ISSUE TITLE
[Feature request] allow users to change *txt icons

### ISSUE THREAD

**Issue by 909101** [0x7c13/Notepads#1286]
**Is your feature request related to a problem? Please describe.**
When set this program as default txt program, the icon of all txt file will be changed to a special designed icon. It looks good, but it would be better if users can get an option to set the icon back to windows' default *txt icon. I believe this feature can make this program to be a better replacement of windows default notepad.

**Describe the solution you'd like**
Allow users to set any icon for their *txt files.

**Describe alternatives you've considered**
Allow users to choose icon for their *txt files between the current (special-designed) icon of this program and windows' default *txt icon.

**Additional context**
Thank you for your amzing work, and I am sorry for raising the number of open issues to exactly 300.

**Comment by 0x7c13** [comment]
You can change the icon yourself and build your own version of Notepads since it is fully open sourced. I don't have problem with current icons and they fit Windows 10/11 pretty well.

**Comment by 909101** [comment]
That's fair enough. Thank u.
