### ISSUE TITLE
[Feature request] 增加对 .bat 文件的右键菜单支持

### ISSUE THREAD

**Issue by yu1t** [0x7c13/Notepads#1293]
`.bat` 文件无法选择打开方式, 只能先打开编辑器再选择 `.bat` 文件进行编辑.
Windows 记事本支持右键菜单编辑
![image](https://github.com/0x7c13/Notepads/assets/21243409/2c6a3f66-b3c8-4943-81f2-37182e1dfb27)

希望 Notepads 能增加针对 `.bat` 格式的右键菜单编辑, `.bat` 的别名还有 `.cmd`

当然也可以同时适用其它文本文件格式

**Comment by 0x7c13** [comment]
因为安全原因UWP App无法注册.bat文件，这个你要找微软
