### ISSUE TITLE
[Bug] It doesn't move towards the words found.

### ISSUE THREAD

**Issue by Zaurio20** [0x7c13/Notepads#1309]
**Describe the bug**
Unlike the Windows notepad, when searching for words, the search engine does not navigate to the found matches when pressing ENTER, it just highlights them.

**To Reproduce**
Press Ctrl + F, enter a word, and press ENTER.

**Expected behavior**
It should move to the found matches when pressing ENTER.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Last Version

**Additional context**

**Comment by 0x7c13** [comment]
I noticed this as well after recent releases. I will look into it.

**Comment by 0x7c13** [comment]
Fixed in this commit: https://github.com/0x7c13/Notepads/commit/595950dd44c59eb431fd841d63122aa42e0a46ba
Will be part of the next release
