### ISSUE TITLE
Enter Key Doesn't Scroll to Found Word in 'Find' Panel

### ISSUE THREAD

**Issue by KinanGH98** [0x7c13/Notepads#1333]
Describe the bug
When using the _Find_ panel in the application and searching for a particular word, pressing the _Enter_ key does not scroll to the found word.

To Reproduce
1. Open the notepad application.
2. Enter some text in the editor.
3. Open the _Find_ panel (Ctrl+F).
4. Type a word to search for in the text.
5. Press the _Enter_ key.

Expected behavior
After pressing the _Enter_ key, the application should scroll to the location of the found word in the text.

Screenshots
![Untitled](https://github.com/0x7c13/Notepads/assets/67392032/6f4db817-4e51-48c3-9a33-de92d68d4831)

Additional context
If you press the _Find Next_ button in the _Find_ panel, the scrolling will happen. Only pressing the _Enter_ key will not work.

 - OS: [Windows 10 22H2 19045.4170]
 - Version [v1.5.4.0]

**Comment by 0x7c13** [comment]
This is fixed in one of the latest commit. I will deploy the changes to Store by EOW.

**Comment by 0x7c13** [comment]
https://github.com/0x7c13/Notepads/commit/595950dd44c59eb431fd841d63122aa42e0a46ba

**Comment by KinanGH98** [comment]
Glad to hear its fixed, thanks.

**Comment by 0x7c13** [comment]
@KinanGH98 The new version containing the fix is on the Store today, please give it a try.

**Comment by KinanGH98** [comment]
> @KinanGH98 The new version containing the fix is on the Store today, please give it a try.

Its fixed indeed, thank you very much for this awesome app.
