### ISSUE TITLE
[Feature request]无法替换换行符，原生记事本支持，希望可以加上

### ISSUE THREAD

**Issue by 0liovoil0** [0x7c13/Notepads#1351]
原生记事本中，从第二行的开头选到第一行的末尾，ctrl+H，替换内容不写，可以把换行符去掉。notepads无法实现，希望可以加上🤞

**Comment by Onion-batch** [comment]
What?

**Comment by nmvjhd** [comment]
打开正则表达式查找，替换\n成空白，全部替换，done

**Comment by Onion-batch** [comment]
I DON'T UNDERSTAND

**Comment by 0liovoil0** [comment]
打开正则表达式查找，替换\n成空白，全部替换，done
