### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by tildejustin** [0x7c13/Notepads#868]
**Is your feature request related to a problem? Please describe.**
Closing the last tab should close the app.

**Describe the solution you'd like**
When the last tab is closed the application should close instead of opening a new document.  There is already a button for that and it seems more intuitive to close the window.  Functionality like chrome.

**Describe alternatives you've considered**
Ctrl+Shift+W could close the window as well.

**Additional context**

**Comment by JTLee98** [comment]
>  Closing the last tab should close the app. 

came here looking for info on this as well, seems like it was brought up a few times in the past:
issue #607 , issue #707 , PR #601 
never seemed to be quite properly resolved though?

**Comment by tildejustin** [comment]
this has been added in the interim
